def print_usage():
    """Print console peer command help."""
    print("\n" + "=" * 65)
    print("  HUONG DAN SU DUNG - TRUE P2P CHAT SYSTEM")
    print("=" * 65)
    print("  /list                            Xem danh sach peers online")
    print("  /connect <user>                  Ket noi P2P truc tiep")
    print("  /msg <user> <noi_dung>           Gui tin; offline se store-forward")
    print("  /offline_msg <user> <noi_dung>   Chu dong gui tin offline")
    print("  /queue_info                      Xem so tin dang cho tren tracker")
    print("  /group create <ten> <u1> <u2>    Tao nhom chat")
    print("  /broadcast <ten_nhom> <noi_dung> Gui tin toi ca nhom")
    print("  /sendfile <user> <path>          Gui file truc tiep")
    print("  /encrypt <user> <shared_key>     Bat ma hoa voi peer")
    print("  /unencrypt <user>                Tat ma hoa voi peer")
    print("  /connections                     Xem ket noi P2P hien tai")
    print("  /disconnect <user>               Dong ket noi P2P")
    print("  /help                            Hien thi huong dan")
    print("  /exit                            Thoat")
    print("=" * 65 + "\n")
